import {
  existsSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import path from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { generate } from '../src/generate.ts'
import { project } from './helpers.ts'

const ORIGIN = {
  'layout.tsx': `
import type { Metadata } from 'next'
export function generateStaticParams() {
  return [{ lang: 'zh' }]
}
export const dynamicParams = false
export async function generateMetadata({ params }: LayoutProps<'/[lang]'>): Promise<Metadata> {
  return { title: (await params).lang }
}
export default async function Layout({ children, params }: LayoutProps<'/[lang]'>) {
  return <html lang={(await params).lang}><body>{children}</body></html>
}
`,
  '(home)/page.tsx': `'use client'
export default function Home() {
  return <h1>home</h1>
}
`,
  'docs/layout.tsx': `
export default function Layout({ children }: { children: React.ReactNode }) {
  return <section>{children}</section>
}
`,
  'docs/[[...slug]]/page.tsx': `
import { withPage } from './page.with'
export function generateStaticParams({ params }: { params: { lang: string } }) {
  return [{ lang: params.lang, slug: ['a'] }]
}
export const dynamicParams = false
export const metadata = { title: 'Docs' }
export async function generateMetadata(props: PageProps<'/[lang]/docs/[[...slug]]'>) {
  return withPage(props)
}
export default async function Page(props: PageProps<'/[lang]/docs/[[...slug]]'>) {
  return withPage(props)
}
`,
  'docs/[[...slug]]/page.with.tsx': `export function withPage(p: unknown) { return p }`,
  'api/[id]/route.ts': `
export const revalidate = false
export const dynamic = 'force-static'
export async function GET(_req: Request, { params }: RouteContext<'/[lang]/api/[id]'>) {
  return Response.json(await params)
}
export function generateStaticParams() {
  return [{ lang: 'zh', id: '1' }]
}
`,
  'opengraph-image.tsx': `
export const alt = 'About'
export const size = { width: 1200, height: 630 }
export const contentType = 'image/png'
export const runtime = 'nodejs'
export default async function Image({ params }: { params: Promise<{ lang: string }> }) {
  return new Response((await params).lang)
}
`,
  'icon.png': 'not really a png',
  'error.tsx': `'use client'
export default function Error() { return null }
`,
  'about/page.jsx': `
export default function About() { return <p>about</p> }
`,
  '_components/nav.tsx': `export const Nav = () => null`,
  'components/footer.tsx': `export const Footer = () => null`,
  'notes.md': '# not a route',
}

const roots: string[] = []
function make(files: Record<string, string> = ORIGIN, options = {}) {
  const root = project(files, options)
  roots.push(root)
  return root
}

afterEach(() => {
  for (const root of roots.splice(0))
    rmSync(root, { recursive: true, force: true })
  vi.restoreAllMocks()
})

function read(root: string, rel: string): string {
  return readFileSync(path.join(root, 'src/app/(unprefixed)', rel), 'utf8')
}

describe('generate', () => {
  it('mirrors every route file and nothing else', () => {
    const root = make()
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    const result = generate({
      cwd: root,
      defaultLocale: 'en',
      localeParam: 'lang',
    })

    expect(result.written.sort()).toEqual(
      [
        '(unprefixed)/.gitignore',
        '(unprefixed)/.manifest.json',
        '(unprefixed)/(home)/page.tsx',
        '(unprefixed)/about/page.jsx',
        '(unprefixed)/api/[id]/route.ts',
        '(unprefixed)/docs/[[...slug]]/page.tsx',
        '(unprefixed)/docs/layout.tsx',
        '(unprefixed)/error.tsx',
        '(unprefixed)/icon.png',
        '(unprefixed)/layout.tsx',
        '(unprefixed)/opengraph-image.tsx',
      ].sort(),
    )
    expect(result.warnings).toEqual([])
    expect(read(root, '.gitignore')).toBe('*\n')
    expect(read(root, 'icon.png')).toBe('not really a png')
  })

  it('pins the locale on a page and repeats its segment config', () => {
    const root = make()
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' })

    expect(read(root, 'docs/[[...slug]]/page.tsx')).toMatchInlineSnapshot(`
      "// Generated by @best-i18n/vinext-unprefixed-locale from [lang]/docs/[[...slug]]/page.tsx.
      // Do not edit: that file is the source, this one only pins the locale to 'en'.

      import { call, pin, render, staticParams } from '@best-i18n/vinext-unprefixed-locale/runtime'
      import * as origin from '../../../[lang]/docs/[[...slug]]/page'
      import type { Arg0, Rest, Unprefixed } from '@best-i18n/vinext-unprefixed-locale/runtime'

      export default function Page(
        props: Unprefixed<Arg0<typeof origin.default>, 'lang'>,
      ) {
        return render(origin.default, pin(props, 'lang', 'en'))
      }

      export function generateMetadata(
        props: Unprefixed<Arg0<typeof origin.generateMetadata>, 'lang'>,
        ...rest: Rest<typeof origin.generateMetadata>
      ) {
        return call(origin.generateMetadata, pin(props, 'lang', 'en'), ...rest)
      }

      export function generateStaticParams(
        props?: { params?: Record<string, unknown> },
      ) {
        return staticParams(origin.generateStaticParams, props, 'lang', 'en')
      }

      export const dynamicParams = false

      export { metadata } from '../../../[lang]/docs/[[...slug]]/page'
      "
    `)
  })

  it("gives a 'use client' page a client wrapper", () => {
    const root = make()
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' })

    const home = read(root, '(home)/page.tsx')
    expect(home.startsWith("'use client'\n")).toBe(true)
    expect(home).toContain(
      "render(origin.default, usePinned(props, 'lang', 'en'))",
    )
    expect(home).not.toContain('staticParams')
    expect(home).not.toContain('metadata')
  })

  it('drops generateStaticParams where the mirrored route has no dynamic segment', () => {
    const root = make()
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' })

    const layout = read(root, 'layout.tsx')
    expect(layout).not.toContain('generateStaticParams')
    expect(layout).toContain('export const dynamicParams = false')
    expect(layout).toContain('export default function Layout(')
    expect(layout).toContain('export function generateMetadata(')
  })

  it('wraps every HTTP method of a route handler', () => {
    const root = make()
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' })

    expect(read(root, 'api/[id]/route.ts')).toMatchInlineSnapshot(`
      "// Generated by @best-i18n/vinext-unprefixed-locale from [lang]/api/[id]/route.ts.
      // Do not edit: that file is the source, this one only pins the locale to 'en'.

      import { call, pin, staticParams } from '@best-i18n/vinext-unprefixed-locale/runtime'
      import * as origin from '../../../[lang]/api/[id]/route'
      import type { Arg0, Arg1, Unprefixed } from '@best-i18n/vinext-unprefixed-locale/runtime'

      export function GET(
        request: Arg0<typeof origin.GET>,
        context: Unprefixed<Arg1<typeof origin.GET>, 'lang'>,
      ) {
        return call(origin.GET, request, pin(context, 'lang', 'en'))
      }

      export function generateStaticParams(
        props?: { params?: Record<string, unknown> },
      ) {
        return staticParams(origin.generateStaticParams, props, 'lang', 'en')
      }

      export const dynamic = 'force-static'
      export const revalidate = false
      "
    `)
  })

  it('re-exports image metadata and repeats the runtime literal', () => {
    const root = make()
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' })

    const image = read(root, 'opengraph-image.tsx')
    expect(image).toContain('export default function Image(')
    expect(image).toContain("export const runtime = 'nodejs'")
    expect(image).toContain(
      "export { alt, size, contentType } from '../[lang]/opengraph-image'",
    )
  })

  it('re-exports boundaries untouched and emits plain JS for a JS origin', () => {
    const root = make()
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' })

    expect(read(root, 'error.tsx')).toContain(
      "export { default } from '../[lang]/error'",
    )
    const about = read(root, 'about/page.jsx')
    expect(about).toContain('export default function Page(props) {')
    expect(about).not.toContain('import type')
    expect(about).not.toContain(': Unprefixed')
  })

  it('is idempotent and prunes wrappers whose origin is gone', () => {
    const root = make()
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' })

    const target = path.join(root, 'src/app/(unprefixed)/api/[id]/route.ts')
    const before = statSync(target).mtimeMs

    const again = generate({
      cwd: root,
      defaultLocale: 'en',
      localeParam: 'lang',
    })
    expect(again.written).toEqual([])
    expect(statSync(target).mtimeMs).toBe(before)

    rmSync(path.join(root, 'src/app/[lang]/api'), { recursive: true })
    const pruned = generate({
      cwd: root,
      defaultLocale: 'en',
      localeParam: 'lang',
    })
    expect(pruned.removed).toEqual(['(unprefixed)/api/[id]/route.ts'])
    expect(existsSync(path.join(root, 'src/app/(unprefixed)/api'))).toBe(false)
  })

  it('warns about segment config it cannot repeat and about export *', () => {
    const root = make({
      'layout.tsx': `export default function L({ children }) { return children }`,
      'page.tsx': `
import { REVALIDATE } from './config'
export * from './config'
export const revalidate = REVALIDATE
export default function Page() { return null }
`,
      'config.ts': `export const REVALIDATE = 60`,
    })
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    vi.spyOn(console, 'warn').mockImplementation(() => {})
    const result = generate({
      cwd: root,
      defaultLocale: 'en',
      localeParam: 'lang',
    })

    expect(result.warnings).toHaveLength(2)
    expect(result.warnings[0]).toContain('export *')
    expect(result.warnings[1]).toContain('`revalidate`')
    expect(read(root, 'page.tsx')).not.toContain('revalidate')
  })

  it('refuses a dynamic segment that would sit beside [lang] at the root', () => {
    const root = make({
      'layout.tsx': `export default function L({ children }) { return children }`,
      '(group)/[slug]/page.tsx': `export default function P() { return null }`,
    })

    expect(() =>
      generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' }),
    ).toThrow(/two dynamic segments/)
  })

  it('refuses a group name that is not a route group', () => {
    const root = make()
    expect(() =>
      generate({
        cwd: root,
        defaultLocale: 'en',
        localeParam: 'lang',
        group: 'en',
      }),
    ).toThrow(/route group/)
  })

  it('explains a missing [locale] directory', () => {
    const root = make()
    expect(() => generate({ cwd: root, defaultLocale: 'en' })).toThrow(
      /\[locale\] does not exist/,
    )
  })

  it('finds app/ when there is no src/app', () => {
    const root = make(
      { 'page.tsx': `export default function P() { return null }` },
      { appDir: 'app', param: 'locale' },
    )
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    const result = generate({ cwd: root, defaultLocale: 'en' })
    expect(result.outputDir).toBe(path.join(root, 'app/(unprefixed)'))
    expect(
      readFileSync(path.join(root, 'app/(unprefixed)/page.tsx'), 'utf8'),
    ).toContain("pin(props, 'locale', 'en')")
  })

  it('honours pageExtensions and passes non-code route files through', () => {
    const root = make({
      'layout.tsx': `export default function L({ children }) { return children }`,
      'blog/page.mdx': `# Hello`,
      'blog/notes.mdx': `# not a route`,
    })
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    const result = generate({
      cwd: root,
      defaultLocale: 'en',
      localeParam: 'lang',
      pageExtensions: ['tsx', 'mdx'],
    })
    expect(result.written).toContain('(unprefixed)/blog/page.mdx')
    expect(result.written).not.toContain('(unprefixed)/blog/notes.mdx')
    expect(read(root, 'blog/page.mdx')).toContain(
      "export * from '../../[lang]/blog/page'",
    )
  })

  it('leaves files it did not write alone when pruning', () => {
    const root = make()
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' })

    const stray = path.join(root, 'src/app/(unprefixed)/hand-written.tsx')
    writeFileSync(stray, 'export {}')
    rmSync(path.join(root, 'src/app/[lang]/about'), { recursive: true })
    generate({ cwd: root, defaultLocale: 'en', localeParam: 'lang' })

    expect(existsSync(stray)).toBe(true)
  })
})
