import type { ModuleExports } from './analyze.ts'

/**
 * The wrapper each kind of route file gets. Pages, layouts and their kin are
 * components that take `params`; route handlers take a `context` with
 * `params`; image files export a function and some constants; the rest need
 * no locale at all and are re-exported as they are.
 */
export type WrapperKind =
  | 'segment'
  | 'handler'
  | 'image'
  | 'reexport'
  | 'reexport-all'

export interface EmitInput {
  kind: WrapperKind
  /** Import specifier of the origin module, relative to the wrapper. */
  specifier: string
  /** The origin's path relative to the app dir, for the header comment. */
  originLabel: string
  exports: ModuleExports
  localeParam: string
  defaultLocale: string
  /** TypeScript origin: the wrapper is annotated so `vinext typegen` can check it. */
  typed: boolean
  /** The mirrored route still has dynamic segments, so it needs static params. */
  dynamic: boolean
  warn: (message: string) => void
}

export const PACKAGE = '@best-i18n/vinext-unprefixed-locale'
export const RUNTIME = `${PACKAGE}/runtime`
export const MARKER = `// Generated by ${PACKAGE} from `

/**
 * Exports Next.js reads by static analysis. Re-exporting the binding would
 * leave Next seeing nothing, so these are repeated as literals - and warned
 * about when the origin did not write a literal.
 */
const SEGMENT_CONFIG = [
  'dynamic',
  'dynamicParams',
  'revalidate',
  'fetchCache',
  'runtime',
  'preferredRegion',
  'maxDuration',
  'experimental_ppr',
]

/** Read from the module at build time, so a plain re-export carries them. */
const STATIC_METADATA = ['metadata', 'viewport']
const IMAGE_METADATA = ['alt', 'size', 'contentType']

const HTTP_METHODS = [
  'GET',
  'HEAD',
  'POST',
  'PUT',
  'DELETE',
  'PATCH',
  'OPTIONS',
]

const COMPONENT_NAMES: Record<string, string> = {
  page: 'Page',
  layout: 'Layout',
  template: 'Template',
  default: 'Default',
}

/**
 * A function declaration laid out the way a formatter would: on one line when
 * it fits, otherwise one parameter per line. A rest parameter takes no
 * trailing comma - that is a syntax error, not a style choice.
 */
function declaration(head: string, params: string[], body: string): string[] {
  const inline = `${head}(${params.join(', ')}) {`
  if (inline.length <= 80) return [inline, `  ${body}`, '}']

  const last = params.length - 1
  return [
    `${head}(`,
    ...params.map((param, index) =>
      index === last && param.startsWith('...') ? `  ${param}` : `  ${param},`,
    ),
    ') {',
    `  ${body}`,
    '}',
  ]
}

export function emitWrapper(input: EmitInput): string {
  const { exports, originLabel, warn } = input
  const q = (value: string) => `'${value.replaceAll("'", "\\'")}'`

  // A client origin gets a client wrapper, so Next renders it through its own
  // client boundary the way it would the origin. See `usePinned` in runtime.
  const client =
    input.kind === 'segment' && exports.directives.includes('use client')

  const header = [
    ...(client ? ["'use client'", ''] : []),
    `${MARKER}${originLabel}.`,
    `// Do not edit: that file is the source, this one only pins the locale to ${q(input.defaultLocale)}.`,
  ]

  if (input.kind === 'reexport-all') {
    return `${[...header, '', `export * from ${q(input.specifier)}`, `export { default } from ${q(input.specifier)}`].join('\n')}\n`
  }

  if (input.kind === 'reexport') {
    return `${[...header, '', `export { default } from ${q(input.specifier)}`].join('\n')}\n`
  }

  if (exports.exportsAll) {
    warn(
      `${originLabel} has an \`export *\`; only the exports it declares itself are mirrored.`,
    )
  }

  const runtime = new Set<string>()
  const types = new Set<string>()
  const body: string[] = []
  const locale = `${q(input.localeParam)}, ${q(input.defaultLocale)}`
  const t = (text: string) => (input.typed ? text : '')

  const unprefixed = (fn: string, arg: 'Arg0' | 'Arg1' = 'Arg0') => {
    if (input.typed) types.add('Unprefixed').add(arg)
    return `Unprefixed<${arg}<typeof origin.${fn}>, ${q(input.localeParam)}>`
  }

  const pinned = (name: string, fn: string) => {
    runtime.add('call').add('pin')
    if (input.typed) types.add('Rest')
    return declaration(
      `export function ${name}`,
      [
        `props${t(`: ${unprefixed(fn)}`)}`,
        `...rest${t(`: Rest<typeof origin.${fn}>`)}`,
      ],
      `return call(origin.${fn}, pin(props, ${locale}), ...rest)`,
    )
  }

  const filename = originLabel.split('/').pop()!.split('.')[0]!

  if (input.kind === 'segment' || input.kind === 'image') {
    if (!exports.names.has('default')) {
      warn(`${originLabel} has no default export; nothing was mirrored.`)
      return ''
    }

    if (input.kind === 'segment') {
      const pinProps = client ? 'usePinned' : 'pin'
      runtime.add('render').add(pinProps)
      body.push(
        ...declaration(
          `export default function ${COMPONENT_NAMES[filename] ?? 'Route'}`,
          [`props${t(`: ${unprefixed('default')}`)}`],
          `return render(origin.default, ${pinProps}(props, ${locale}))`,
        ),
      )
      // A client module cannot export these, so a client origin has none.
      for (const name of ['generateMetadata', 'generateViewport']) {
        if (exports.names.has(name)) body.push('', ...pinned(name, name))
      }
    } else {
      runtime.add('call').add('pin')
      body.push(
        ...declaration(
          'export default function Image',
          [`props${t(`: ${unprefixed('default')}`)}`],
          `return call(origin.default, pin(props, ${locale}))`,
        ),
      )
      if (exports.names.has('generateImageMetadata')) {
        body.push(
          '',
          ...pinned('generateImageMetadata', 'generateImageMetadata'),
        )
      }
    }
  }

  if (input.kind === 'handler') {
    const methods = HTTP_METHODS.filter((method) => exports.names.has(method))
    if (methods.length === 0) {
      warn(`${originLabel} exports no HTTP method; nothing was mirrored.`)
      return ''
    }
    runtime.add('call').add('pin')
    for (const method of methods) {
      if (body.length > 0) body.push('')
      if (input.typed) types.add('Arg0')
      body.push(
        ...declaration(
          `export function ${method}`,
          [
            `request${t(`: Arg0<typeof origin.${method}>`)}`,
            `context${t(`: ${unprefixed(method, 'Arg1')}`)}`,
          ],
          `return call(origin.${method}, request, pin(context, ${locale}))`,
        ),
      )
    }
  }

  if (exports.names.has('generateStaticParams') && input.dynamic && !client) {
    runtime.add('staticParams')
    body.push(
      '',
      ...declaration(
        'export function generateStaticParams',
        [`props${t('?: { params?: Record<string, unknown> }')}`],
        `return staticParams(origin.generateStaticParams, props, ${locale})`,
      ),
    )
  }

  const literals: string[] = []
  for (const name of SEGMENT_CONFIG) {
    if (!exports.names.has(name)) continue
    const literal = exports.literals.get(name)
    if (literal === undefined) {
      warn(
        `${originLabel} exports \`${name}\` as something other than a literal. Next.js reads route segment config statically, so the mirror cannot repeat it; write the value inline.`,
      )
      continue
    }
    literals.push(`export const ${name} = ${literal}`)
  }
  if (literals.length > 0) body.push('', ...literals)

  const reexported = (
    input.kind === 'image' ? IMAGE_METADATA : STATIC_METADATA
  ).filter((name) => exports.names.has(name) && !client)
  if (reexported.length > 0) {
    body.push(
      '',
      `export { ${reexported.join(', ')} } from ${q(input.specifier)}`,
    )
  }

  const imports = [
    `import { ${[...runtime].sort().join(', ')} } from ${q(RUNTIME)}`,
    `import * as origin from ${q(input.specifier)}`,
  ]
  if (input.typed && types.size > 0) {
    imports.push(
      `import type { ${[...types].sort().join(', ')} } from ${q(RUNTIME)}`,
    )
  }

  return `${[...header, '', ...imports, '', ...body].join('\n')}\n`
}
